### ISSUE TITLE
Calling stdin.readline() multiple times only works the first time.

### ISSUE THREAD

**Issue by RIZY101** [pedro823/ctf-nc-framework#1]
When using
```
name = stdin.readline().strip()
stdout.write(name)
stdout.flush()
password = stdin.readline().strip()
stdout.write(password)
stdout.flush()
```
only the name prints out

**Comment by pedro823** [comment]
Will check it out soon 👀 

This is the source code of your `main` function inside `src/main.py`, right?

**Comment by pedro823** [comment]
Hey! Can you confirm that version v0.1.1 of the framework fixes this?

**Comment by RIZY101** [comment]
> Hey! Can you confirm that version v0.1.1 of the framework fixes this?

Sorry I did not get back to you sooner, but yes version 0.1.1 fixed the issue. Thanks for your help!
